[package]
name = "termt"
version = "0.1.0"
authors = ["alan <leftwo@gmail.com>"]
edition = "2018"
description = "Terminal based Tetris"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.17.5"
